Order vulnerabilities by severity #35
aquasecurity/starboard-lens-extension pull request #40
Opened 2020-12-17 07:29 UTC by YoussefEgla

2020-12-18 19:20 UTC, YoussefEgla commented
Testing suite failed due to undefined value in `extension-api.js`

```
```

2020-12-18 19:23 UTC, YoussefEgla commented
Test suite fails due to undefined value passed instead of a string in `extension-api.js` in `@k8slens` package

```
> @aquasecurity/starboard-lens-extension@0.0.1-alpha.7 test U:\starboard-lens-extension
> jest

 FAIL  src/components/vulnerabilities-list.test.tsx
  ● Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

      at new Ee.constructor (node_modules/@k8slens/extensions/dist/src/extensions/extension-api.js:883:1651768)
      at new <anonymous> (node_modules/@k8slens/extensions/dist/src/extensions/extension-api.js:883:1653852)
      at Module.<anonymous> (node_modules/@k8slens/extensions/dist/src/extensions/extension-api.js:883:1651338)
      at r (node_modules/@k8slens/extensions/dist/src/extensions/extension-api.js:1:247)
      at node_modules/@k8slens/extensions/dist/src/extensions/extension-api.js:1:1046
      at Object.<anonymous> (node_modules/@k8slens/extensions/dist/src/extensions/extension-api.js:1:1058)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        16.426 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

2020-12-19 01:09 UTC, danielpacak requested changes
@YoussefEgla I think that for ordering a list of Vulnerability objects by severity we should strive for a simple solution that works. And then maybe in subsequent PRs we could introduce testing frameworks and focus on refactoring. Also there's no point in adding lots of new dependencies and tests that are failing.

2020-12-19 01:09 UTC, danielpacak commented on src/vulnerability-report.ts
> +    //
You can leave such comment as PR comment, but it's not useful as part of the source code.

2020-12-19 08:31 UTC, YoussefEgla commented
thanks so much for this comprehensive review You are right the built in sort method will do in order, i didn't notice

2020-12-23 15:39 UTC, danielpacak commented
These changes are huge, break the build, have failing tests, and do not sort vulnerabilities by severity. Closing in favour of smaller PRs that actually work.

2020-12-23 15:39 UTC, closed without merging