feat: Show color badges for severity on reports lists
aquasecurity/starboard-lens-extension pull request #84
Opened 2022-04-21 21:02 UTC by nublarsec

This change adds color badges to the severity counts on the report list pages, making them easier to scan visually.

This resolves issue #83.

Vulnerability Reports page:
<img width="1329" alt="Screen Shot 2022-04-21 at 1 01 58 PM" src="https://user-images.githubusercontent.com/103554953/164551405-a2cc340a-a064-4c34-8bae-aeb1ba3a1447.png">

Config Audit Reports page:
<img width="1334" alt="Screen Shot 2022-04-21 at 1 54 18 PM" src="https://user-images.githubusercontent.com/103554953/164551429-2b4b6b4f-869a-4d27-a73d-e804d34f41cc.png">

CIS Kube Bench Reports page:
<img width="1336" alt="Screen Shot 2022-04-21 at 1 54 27 PM" src="https://user-images.githubusercontent.com/103554953/164551464-5d1fcc7b-c129-4a81-b4cc-c1642977e316.png">

2022-04-21 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/starboard-lens-extension?pullRequest=84) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/starboard-lens-extension?pullRequest=84) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/starboard-lens-extension?pullRequest=84) it.</sub>

2022-04-22 09:36 UTC, danielpacak requested changes
Great idea @nublarsec and thanks for working on the implementation. I left minor comments to apply. I also noticed that the text is not exactly centered.

![lens_badges](https://user-images.githubusercontent.com/1322923/164679513-5e14659d-6b98-41ee-abd2-0e49884a1015.png)

2022-04-22 09:36 UTC, danielpacak commented on src/configauditreports/page.scss
> +    }
For configuration audits we only have Critical, High, Medium, and Low severities.

2022-04-22 09:36 UTC, danielpacak commented on src/vulnerabilityreports/page.scss
> +    }
We don't use Negligible severity in anymore.

2022-04-22 14:48 UTC, nublarsec commented
@danielpacak thanks for the quick reply. I've dropped the unused severity styles. 

I also changed the badges for zero counts so they still appear with the same size and shape. This looks better and keeps all the counts aligned.

2022-04-22 15:20 UTC, danielpacak approved these changes

2022-04-22 15:20 UTC, merged